name: hero_chum
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.1
  get: ^4.6.6
  rive: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/leaf_mark.png
    - assets/map_styles/style_dark.json
    - assets/map_styles/style_full_standard.json
    - assets/map_styles/style_silver.json
    - assets/images/logo_text.png
    - assets/images/login_motto.png
    - assets/animations/herochums.riv


