name: hero_chum
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.1
  get: ^4.6.6
  rive: ^0.13.7
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter_animarker: ^3.2.0
  flutter_gemini: ^2.0.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/leaf_mark.png
    - assets/images/custom_mark.png
    - assets/images/logo_text.png
    - assets/images/login_motto.png
    - assets/images/logo.png
    - assets/images/avatars/.
    - assets/images/trash-2-cans.jpg

    - assets/animations/herochums.riv
    - assets/animations/sad_square_idle.riv

    - assets/map_styles/style_dark.json
    - assets/map_styles/style_full_standard.json
    - assets/map_styles/style_silver.json

